[[redirects]]
  from = "/api/:function"
  to = "/.netlify/functions/:function"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://aaronfpp.github.io/image-scraper/:splat"
  status = 301
  force = true


[build]
  command = "npm run build"
  functions = "functions"
  publish = "."
  environment = { NODE_VERSION = "18", CI = "false" }
