[[redirects]]
  from = "/api/fetch-image/*"
  to = "/.netlify/functions/fetch-image"
  status = 200

[build]
  command = "npm run build"
  functions = "functions"
  publish = "."
  environment = {
    NODE_VERSION = "18"
    CI = "false"
    NODE_ENV = "production"
  }
